import argparse
import os
import sqlite3
from typing import Iterable

import psycopg


BASE_TABLES = {
    "users": """
        CREATE TABLE IF NOT EXISTS users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT NOT NULL UNIQUE,
            created_at TEXT NOT NULL
        )
    """,
    "counterparties": """
        CREATE TABLE IF NOT EXISTS counterparties (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            type TEXT NOT NULL,
            name TEXT NOT NULL,
            phone TEXT,
            email TEXT,
            inn TEXT,
            company_name TEXT,
            notes TEXT,
            created_at TEXT NOT NULL,
            full_name TEXT,
            kpp TEXT,
            ogrn TEXT,
            ogrnip TEXT,
            passport_series_number TEXT,
            passport_issued_by TEXT,
            passport_department_code TEXT,
            registration_address TEXT,
            work_address TEXT,
            birth_date TEXT,
            checking_account TEXT,
            correspondent_account TEXT,
            bank_name TEXT,
            bank_bik TEXT,
            legal_address TEXT,
            postal_address TEXT,
            actual_address TEXT,
            director_name TEXT,
            director_basis TEXT
        )
    """,
    "projects": """
        CREATE TABLE IF NOT EXISTS projects (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            address TEXT,
            customer TEXT,
            contract TEXT,
            date TEXT,
            project_name TEXT,
            counterparty_id BIGINT,
            status TEXT DEFAULT 'Черновик',
            notes TEXT,
            created_at TEXT,
            updated_at TEXT,
            contract_settings_json TEXT
        )
    """,
    "documents": """
        CREATE TABLE IF NOT EXISTS documents (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            project_id BIGINT NOT NULL,
            doc_type TEXT NOT NULL,
            title TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'Черновик',
            file_path TEXT,
            version BIGINT NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            draft_path TEXT,
            pdf_path TEXT
        )
    """,
    "project_events": """
        CREATE TABLE IF NOT EXISTS project_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            project_id BIGINT NOT NULL,
            event_type TEXT NOT NULL,
            event_text TEXT NOT NULL,
            created_at TEXT NOT NULL,
            author TEXT
        )
    """,
    "smeta_drafts": """
        CREATE TABLE IF NOT EXISTS smeta_drafts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT NOT NULL,
            data TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            created_by TEXT,
            created_at TEXT,
            updated_by TEXT
        )
    """,
    "cash_transactions": """
        CREATE TABLE IF NOT EXISTS cash_transactions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            txn_date TEXT NOT NULL,
            txn_type TEXT NOT NULL,
            amount DOUBLE PRECISION NOT NULL,
            project_id BIGINT,
            counterparty_id BIGINT,
            category TEXT,
            description TEXT,
            created_at TEXT NOT NULL,
            created_by TEXT
        )
    """,
    "prices": """
        CREATE TABLE IF NOT EXISTS prices (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT,
            unit TEXT,
            price DOUBLE PRECISION
        )
    """,
}

IMPORT_ORDER = [
    "users",
    "counterparties",
    "projects",
    "documents",
    "project_events",
    "smeta_drafts",
    "cash_transactions",
    "prices",
]


def parse_args():
    parser = argparse.ArgumentParser(
        description="Migrate Dekorartstroy CRM SQLite data into PostgreSQL."
    )
    parser.add_argument(
        "--pg-dsn",
        default=os.environ.get("POSTGRES_DSN", ""),
        help="PostgreSQL DSN. Can also be provided via POSTGRES_DSN.",
    )
    parser.add_argument(
        "--base-db",
        default="dekorart_base.db",
        help="Path to the main SQLite database.",
    )
    parser.add_argument(
        "--prices-db",
        default="dekorart_prices.db",
        help="Path to the prices SQLite database.",
    )
    parser.add_argument(
        "--no-reset",
        action="store_true",
        help="Do not drop and recreate target tables before import.",
    )
    return parser.parse_args()


def fetch_sqlite_rows(db_path: str, table_name: str):
    if not os.path.exists(db_path):
        return [], []
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()
    tables = {
        row["name"]
        for row in cur.execute(
            "SELECT name FROM sqlite_master WHERE type='table'"
        ).fetchall()
    }
    if table_name not in tables:
        conn.close()
        return [], []
    rows = cur.execute(f'SELECT * FROM "{table_name}" ORDER BY id').fetchall()
    column_names = [desc[0] for desc in cur.description]
    data = [[row[column] for column in column_names] for row in rows]
    conn.close()
    return column_names, data


def reset_schema(pg_conn):
    with pg_conn.cursor() as cur:
        for table_name in reversed(IMPORT_ORDER):
            cur.execute(f'DROP TABLE IF EXISTS "{table_name}" CASCADE')
        for table_name in IMPORT_ORDER:
            cur.execute(BASE_TABLES[table_name])
    pg_conn.commit()


def ensure_schema(pg_conn):
    with pg_conn.cursor() as cur:
        for table_name in IMPORT_ORDER:
            cur.execute(BASE_TABLES[table_name])
    pg_conn.commit()


def chunked(rows: list[list], size: int = 500) -> Iterable[list[list]]:
    for index in range(0, len(rows), size):
        yield rows[index : index + size]


def import_table(pg_conn, table_name: str, columns: list[str], rows: list[list]):
    if not columns:
        return 0
    quoted_columns = ", ".join(f'"{column}"' for column in columns)
    placeholders = ", ".join(["%s"] * len(columns))
    sql = f'INSERT INTO "{table_name}" ({quoted_columns}) VALUES ({placeholders})'
    inserted = 0
    with pg_conn.cursor() as cur:
        for batch in chunked(rows):
            cur.executemany(sql, batch)
            inserted += len(batch)
        if "id" in columns:
            max_id = max((row[columns.index("id")] for row in rows), default=0) or 0
            cur.execute(
                "SELECT pg_get_serial_sequence(%s, %s)",
                (table_name, "id"),
            )
            sequence_name = cur.fetchone()[0]
            if sequence_name and max_id > 0:
                cur.execute(
                    "SELECT setval(%s::regclass, %s, %s)",
                    (sequence_name, max_id, bool(max_id)),
                )
    pg_conn.commit()
    return inserted


def main():
    args = parse_args()
    if not args.pg_dsn:
        raise SystemExit("Provide PostgreSQL DSN via --pg-dsn or POSTGRES_DSN.")

    pg_conn = psycopg.connect(args.pg_dsn)
    try:
        if args.no_reset:
            ensure_schema(pg_conn)
        else:
            reset_schema(pg_conn)

        sources = {
            "users": args.base_db,
            "counterparties": args.base_db,
            "projects": args.base_db,
            "documents": args.base_db,
            "project_events": args.base_db,
            "smeta_drafts": args.base_db,
            "cash_transactions": args.base_db,
            "prices": args.prices_db,
        }

        for table_name in IMPORT_ORDER:
            columns, rows = fetch_sqlite_rows(sources[table_name], table_name)
            inserted = import_table(pg_conn, table_name, columns, rows)
            print(f"{table_name}: {inserted}")
    finally:
        pg_conn.close()


if __name__ == "__main__":
    main()
