BEGIN;

CREATE TABLE IF NOT EXISTS companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legal_name TEXT NOT NULL,
    short_name TEXT NOT NULL UNIQUE,
    inn TEXT,
    kpp TEXT,
    ogrn TEXT,
    ogrnip TEXT,
    legal_address TEXT,
    phone TEXT,
    email TEXT,
    website TEXT,
    bank_name TEXT,
    bik TEXT,
    account TEXT,
    correspondent_account TEXT,
    director_name TEXT,
    signer_name TEXT,
    stamp_path TEXT,
    signature_path TEXT,
    watermark_text TEXT NOT NULL DEFAULT 'ДЕКОРАРТСТРОЙ',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_companies_short_name ON companies (short_name);
CREATE INDEX IF NOT EXISTS idx_companies_is_active ON companies (is_active);

INSERT INTO companies (legal_name, short_name, inn, kpp, ogrn, legal_address, phone, email, website, director_name, watermark_text, created_at, updated_at)
VALUES (
    'ООО «Декорартстрой»',
    'ООО Декорартстрой',
    '7811530330',
    '780501001',
    '1127847464942',
    'г. Санкт-Петербург, Ленинский пр-кт, д. 144, кор. 1, стр. 2, оф. 302',
    '+7 (911) 921-30-39, +7 (911) 031-61-01',
    'info@dekorartstroy.ru',
    'remontstroyspb.ru',
    NULL,
    'ДЕКОРАРТСТРОЙ',
    now()::text,
    now()::text
);

INSERT INTO companies (legal_name, short_name, inn, ogrnip, legal_address, phone, email, website, director_name, watermark_text, created_at, updated_at)
VALUES (
    'ИП Гордеев А.Н.',
    'ИП Гордеев А.Н.',
    '781144532689',
    '318784700361262',
    'г. Санкт-Петербург, Ленинский пр-кт, д. 144, кор. 1, стр. 2, оф. 302',
    '+7 (911) 921-30-39, +7 (911) 031-61-01',
    'gorodok198@yandex.ru',
    'remontstroyspb.ru',
    'Гордеев Алексей Николаевич',
    'ИП ГОРДЕЕВ А.Н.',
    now()::text,
    now()::text
);

COMMIT;