BEGIN;

CREATE TABLE IF NOT EXISTS estimates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_number TEXT NOT NULL,
    title TEXT,
    status TEXT NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'sent', 'approved', 'in_progress', 'rejected')),
    estimate_type TEXT NOT NULL DEFAULT 'primary'
        CHECK (estimate_type IN ('primary', 'additional', 'supplement')),
    origin_channel TEXT NOT NULL DEFAULT 'web'
        CHECK (origin_channel IN ('web', 'telegram', 'system')),
    project_id BIGINT NULL,
    counterparty_id BIGINT NULL,
    parent_estimate_id BIGINT NULL,
    root_estimate_id BIGINT NULL,
    current_version_id BIGINT NULL,
    approved_version_id BIGINT NULL,
    final_document_id BIGINT NULL,
    customer_name TEXT,
    object_name TEXT,
    company_name TEXT,
    contract_label TEXT,
    discount DECIMAL(12, 2) NOT NULL DEFAULT 0,
    watermark TEXT,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_by TEXT,
    updated_by TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    sent_at TEXT,
    approved_at TEXT,
    rejected_at TEXT,
    project_created_at TEXT,
    CONSTRAINT fk_estimates_project
        FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL,
    CONSTRAINT fk_estimates_counterparty
        FOREIGN KEY (counterparty_id) REFERENCES counterparties(id) ON DELETE SET NULL,
    CONSTRAINT fk_estimates_parent
        FOREIGN KEY (parent_estimate_id) REFERENCES estimates(id) ON DELETE SET NULL,
    CONSTRAINT fk_estimates_root
        FOREIGN KEY (root_estimate_id) REFERENCES estimates(id) ON DELETE SET NULL,
    CONSTRAINT fk_estimates_final_document
        FOREIGN KEY (final_document_id) REFERENCES documents(id) ON DELETE SET NULL,
    CONSTRAINT chk_estimates_project_created_at_requires_project
        CHECK (project_created_at IS NULL OR project_id IS NOT NULL),
    CONSTRAINT chk_estimates_approved_at_requires_status
        CHECK (approved_at IS NULL OR status IN ('approved', 'in_progress')),
    CONSTRAINT chk_estimates_sent_at_requires_status
        CHECK (sent_at IS NULL OR status IN ('sent', 'approved', 'in_progress', 'rejected')),
    CONSTRAINT chk_estimates_rejected_at_requires_status
        CHECK (rejected_at IS NULL OR status = 'rejected')
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_estimates_estimate_number
    ON estimates (estimate_number);
CREATE INDEX IF NOT EXISTS idx_estimates_project_id
    ON estimates (project_id);
CREATE INDEX IF NOT EXISTS idx_estimates_counterparty_id
    ON estimates (counterparty_id);
CREATE INDEX IF NOT EXISTS idx_estimates_parent_estimate_id
    ON estimates (parent_estimate_id);
CREATE INDEX IF NOT EXISTS idx_estimates_root_estimate_id
    ON estimates (root_estimate_id);
CREATE INDEX IF NOT EXISTS idx_estimates_status
    ON estimates (status);
CREATE INDEX IF NOT EXISTS idx_estimates_type
    ON estimates (estimate_type);

CREATE TABLE IF NOT EXISTS estimate_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_id BIGINT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    row_type TEXT NOT NULL DEFAULT 'item'
        CHECK (row_type IN ('section', 'item')),
    parent_section_id BIGINT NULL,
    section_key TEXT,
    name TEXT NOT NULL,
    unit TEXT,
    quantity DECIMAL(12, 3),
    price DECIMAL(12, 2),
    total DECIMAL(12, 2),
    discounted_total DECIMAL(12, 2),
    reference TEXT,
    price_source_type TEXT,
    price_source_id BIGINT NULL,
    is_manual_price BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT fk_estimate_items_estimate
        FOREIGN KEY (estimate_id) REFERENCES estimates(id) ON DELETE CASCADE,
    CONSTRAINT fk_estimate_items_parent_section
        FOREIGN KEY (parent_section_id) REFERENCES estimate_items(id) ON DELETE SET NULL,
    CONSTRAINT chk_estimate_items_totals_nonnegative
        CHECK (
            COALESCE(quantity, 0) >= 0
            AND COALESCE(price, 0) >= 0
            AND COALESCE(total, 0) >= 0
            AND COALESCE(discounted_total, 0) >= 0
        )
);

CREATE INDEX IF NOT EXISTS idx_estimate_items_estimate_sort
    ON estimate_items (estimate_id, sort_order, id);
CREATE INDEX IF NOT EXISTS idx_estimate_items_parent_section_id
    ON estimate_items (parent_section_id);
CREATE INDEX IF NOT EXISTS idx_estimate_items_price_source
    ON estimate_items (price_source_type, price_source_id);

CREATE TABLE IF NOT EXISTS estimate_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    version_kind TEXT NOT NULL
        CHECK (version_kind IN ('draft', 'sent', 'approved', 'project_copy', 'supplement')),
    status_at_save TEXT NOT NULL
        CHECK (status_at_save IN ('draft', 'sent', 'approved', 'in_progress', 'rejected')),
    snapshot_json TEXT NOT NULL,
    calc_state_json TEXT,
    is_final BOOLEAN NOT NULL DEFAULT FALSE,
    stamp_applied BOOLEAN NOT NULL DEFAULT FALSE,
    signature_applied BOOLEAN NOT NULL DEFAULT FALSE,
    document_id BIGINT NULL,
    pdf_document_id BIGINT NULL,
    change_comment TEXT,
    source_event TEXT,
    created_by TEXT,
    created_at TEXT NOT NULL,
    CONSTRAINT fk_estimate_versions_estimate
        FOREIGN KEY (estimate_id) REFERENCES estimates(id) ON DELETE CASCADE,
    CONSTRAINT fk_estimate_versions_document
        FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE SET NULL,
    CONSTRAINT fk_estimate_versions_pdf_document
        FOREIGN KEY (pdf_document_id) REFERENCES documents(id) ON DELETE SET NULL,
    CONSTRAINT uq_estimate_versions_per_estimate
        UNIQUE (estimate_id, version_number),
    CONSTRAINT chk_estimate_versions_signature_stamp_final_only
        CHECK (
            (stamp_applied = FALSE AND signature_applied = FALSE)
            OR (
                is_final = TRUE
                AND version_kind = 'approved'
                AND status_at_save = 'approved'
            )
        ),
    CONSTRAINT chk_estimate_versions_final_requires_approved
        CHECK (
            is_final = FALSE
            OR (
                version_kind = 'approved'
                AND status_at_save = 'approved'
            )
        )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_estimate_versions_final_one_per_estimate
    ON estimate_versions (estimate_id)
    WHERE is_final = TRUE;
CREATE INDEX IF NOT EXISTS idx_estimate_versions_estimate_id
    ON estimate_versions (estimate_id, version_number DESC);
CREATE INDEX IF NOT EXISTS idx_estimate_versions_document_id
    ON estimate_versions (document_id);
CREATE INDEX IF NOT EXISTS idx_estimate_versions_pdf_document_id
    ON estimate_versions (pdf_document_id);

CREATE TABLE IF NOT EXISTS estimate_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_id BIGINT NOT NULL,
    old_status TEXT
        CHECK (old_status IS NULL OR old_status IN ('draft', 'sent', 'approved', 'in_progress', 'rejected')),
    new_status TEXT NOT NULL
        CHECK (new_status IN ('draft', 'sent', 'approved', 'in_progress', 'rejected')),
    comment TEXT,
    changed_by TEXT,
    changed_at TEXT NOT NULL,
    CONSTRAINT fk_estimate_status_history_estimate
        FOREIGN KEY (estimate_id) REFERENCES estimates(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_estimate_status_history_estimate_id
    ON estimate_status_history (estimate_id, changed_at DESC);

CREATE TABLE IF NOT EXISTS estimate_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_id BIGINT NOT NULL,
    estimate_version_id BIGINT NULL,
    document_id BIGINT NOT NULL,
    kind TEXT NOT NULL
        CHECK (kind IN ('draft_json', 'draft_pdf', 'approved_pdf', 'project_copy_pdf', 'supplement_pdf', 'signed_pdf')),
    is_current BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TEXT NOT NULL,
    CONSTRAINT fk_estimate_documents_estimate
        FOREIGN KEY (estimate_id) REFERENCES estimates(id) ON DELETE CASCADE,
    CONSTRAINT fk_estimate_documents_version
        FOREIGN KEY (estimate_version_id) REFERENCES estimate_versions(id) ON DELETE SET NULL,
    CONSTRAINT fk_estimate_documents_document
        FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_estimate_documents_estimate_id
    ON estimate_documents (estimate_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_estimate_documents_version_id
    ON estimate_documents (estimate_version_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_estimate_documents_current_kind
    ON estimate_documents (estimate_id, kind)
    WHERE is_current = TRUE;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_estimates_current_version'
    ) THEN
        ALTER TABLE estimates
            ADD CONSTRAINT fk_estimates_current_version
            FOREIGN KEY (current_version_id) REFERENCES estimate_versions(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_estimates_approved_version'
    ) THEN
        ALTER TABLE estimates
            ADD CONSTRAINT fk_estimates_approved_version
            FOREIGN KEY (approved_version_id) REFERENCES estimate_versions(id) ON DELETE SET NULL;
    END IF;
END $$;

COMMIT;
